In [3]:
def f (x) :
    
    return x ** 3 + 2 * x - 2

def racine (N) :
    
    import matplotlib.pyplot as plt
    import numpy as np
    
    intervalle = [0,0.5,1]
    compteur = 0
    
    while compteur < N :
        if f(intervalle[0]) * f(intervalle[1]) < 0 :
            intervalle = [intervalle[0],(intervalle[0]+intervalle[1])/2,intervalle[1]]
        else :
            intervalle = [intervalle[1],(intervalle[1]+intervalle[2])/2,intervalle[2]]
        compteur = compteur + 1
        
    return intervalle

print(racine(10))    

[0.7705078125, 0.77099609375, 0.771484375]


In [9]:
import numpy as np

a = np.array([[2, 9, 5], [7, 5, 3], [6, 1, 8]])
print(a)



[[2 9 5]
 [7 5 3]
 [6 1 8]]
